<?php

namespace App\Repository;

use App\Model\SearchPropertyDTO;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findLast9Properties(): array
    {
        return $this->createQueryBuilder('p')
            ->join('p.agency', 'a')
            ->addSelect('a')
            ->setMaxResults(9)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param SearchPropertyDTO $searchPropertyDTO
     *
     * @return array
     */
    public function findAllProperties(SearchPropertyDTO $searchPropertyDTO): array
    {
        $query = $this->createQueryBuilder('p')
            ->join('p.agency', 'a')
            ->addSelect('a');

        if ($searchPropertyDTO->getType()) {
            $query = $query
                ->andWhere('p.type = :type')
                ->setParameter('type', $searchPropertyDTO->getType());
        }

        if ($searchPropertyDTO->getDepartment()) {
            $query = $query
                ->andWhere('p.department = :department')
                ->setParameter('department', $searchPropertyDTO->getDepartment());
        }

        if ($searchPropertyDTO->getMinPrice()) {
            $query = $query
                ->andWhere('p.price >= :minPrice')
                ->setParameter('minPrice', $searchPropertyDTO->getMinPrice());
        }

        if ($searchPropertyDTO->getMaxPrice()) {
            $query = $query
                ->andWhere('p.price <= :maxPrice')
                ->setParameter('maxPrice', $searchPropertyDTO->getMaxPrice());
        }

        return $query->getQuery()->getResult();
    }
}
