app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path: /connexion
    defaults:
        _controller: AppBundle:Platform\Security:connection

login_check:
    path: /login_check

logout:
    path: /logout